### ISSUE TITLE
Customizr 3.5.15 Issue switching theme desktop/mobile

### ISSUE THREAD

**Issue by PeopleInside** [Nikeo/customizr#966] opened 2017-06-16 22:25 UTC
Hi,
in my [website](https://www.peopleinside.it) 
if I resize the browser window I see a blank space on the start of the page on Firefox and also Chrome, if I scroll down the page in the mobile view and scroll up again seems the issue is automatically fixed.
When I resize to full screen (desktop) the windows again ... part of the page are showed under the menu.

This (page under the menu) was present also sometimes when a PC load my website for the first time... seems the page is back to the menu sometimes and scrolling down the issue is fixed when you go up again.

I made a short video, maybe from the video and from visiting my website you can found a fix and improve code of the theme.

https://www.screencast.com/t/kfV0Gash

**Comment by eri-trabiccolo** [comment] 2017-06-17 17:40
Hi @PeopleInside 
thanks for reporting this.
We've fixed it, a new version will be released soon.

duplicate of #963 
fixed in https://github.com/presscustomizr/customizr/commit/2050078f6ffad4455100cee1ef4a35d1ad4b7b7c

**Closed as completed by eri-trabiccolo** 2017-06-17 17:40 UTC
Labels: duplicate, fixed
