### ISSUE TITLE
Missing rtl editor style css 

### ISSUE THREAD

**Issue by elico** [Nikeo/customizr#937] opened 2017-06-09 15:32 UTC
When I am editing a page I am recieving the next error in a pop up:

> Failed to load content css: http://ngtech.co.il/lectures-he/wp-content/themes/customizr/assets/back/css/editor-style-rtl.css

I am using latest wordpress.

**Comment by eri-trabiccolo** [comment] 2017-06-09 15:39
Hi @elico,
thanks for reporting this.
We're about to release a fix :D 

duplicate of #926

**Comment by eri-trabiccolo** [comment] 2017-06-10 08:29
Hi elico,
fixed in v3.5.14

**Closed as completed by eri-trabiccolo** 2017-06-10 08:29 UTC
Labels: bug, fixed

**Comment by elico** [comment] 2017-06-10 18:31
Thanks. 
Will test today.
