### ISSUE TITLE
Header color lost in latest version 4.1.17

### ISSUE THREAD

**Issue by ghost** [Nikeo/customizr#1602] opened 2018-10-09 22:05 UTC
https://wordpress.org/support/topic/header-color-lost-in-latest-version-4-1-17/

> Hi
> I upgraded to 4.1.17 and now the header is transparent!
> I made no changes other than the upgrade.
> You can see the problem on the site http://www.linkedinspirit.net
> 
> When customizing, it shows the header with the color, but that color goes when you go to the site.
> please help this is urgent!
> thanks
> Phil

> BTW I changed the color, reverted to standard customizr theme and it made no difference.

**Comment by ghost** [comment] 2018-10-09 22:05
@eri-trabiccolo thanks for taking a look

**Comment by eri-trabiccolo** [comment] 2018-10-09 22:43
Hi,
I will tomorrow morning :)
Honestly I'm not sure this is a bug, I tested the code but I might have missed this particular case. Though... the issue might also happen only on that website (cache? child-theme?).
Anyway we'll see...

**Comment by eri-trabiccolo** [comment] 2018-10-10 06:48
@Nikeo cannot reproduce.
User need to clean the plugins cache (e.g. autoptimize).
Here's his site "excluding" autoptimize: http://www.linkedinspirit.net/?ao_noptimize=1

**Comment by eri-trabiccolo** [comment] 2018-10-17 13:18
I close this, the user website works.

**Closed as completed by eri-trabiccolo** 2018-10-17 13:18 UTC
Labels: bug, question, [Priority:urgent], cant-reproduce, 2-ms
