### ISSUE TITLE
[ Customizr Pro Theme ] Front page content category filter option not working

### ISSUE THREAD

**Issue by denzelchia** [Nikeo/customizr#1320] opened 2017-11-27 04:04 UTC
Hi @Nikeo ,

Please refer to the following ticket on helpscout.
https://secure.helpscout.net/conversation/474175016/34788?folderId=631714

I am able to replicate customer's issue, using information provided by customer in his latest reply.

This happens in classical design.
In my current test, I do not have any sticky posts, I am using grid layout with grid customizer enabled.
I have posts attached to "Featured" category. But does not filter when I select "Featured" in  the option -> Apply a category filter to your home / blog posts.

Please see screen-cast of my test.
http://screencast-o-matic.com/watch/cbXteJ2v30

The following is my system information.

```
SITE_URL:                 http://localhost/customizr-pro
HOME_URL:                 http://localhost/customizr-pro
IS MULTISITE :            No

THEME | VERSION :         customizr-pro | v2.0.18# WP VERSION :              4.9
PERMALINK STRUCTURE :     /%postname%/

 ACTIVE PLUGINS :

PHP Version:              7.1.0
MySQL Version:            5.6.34
Web Server Info:          Apache/2.2.31 (Unix) mod_wsgi/3.5 Python/2.7.12 PHP/7.1.0 mod_ssl/2.2.31 OpenSSL/1.0.2j DAV/2 mod_fastcgi/2.4.6 mod_perl/2.0.9 Perl/v5.24.0

WordPress Memory Limit:   40MB
PHP Memory Limit:         256M
PHP Upload Max Size:      32M
PHP Post Max Size:        32M
PHP Upload Max Filesize:  32M
PHP Time Limit:           30
PHP Max Input Vars:       1000
PHP Arg Separator:        &
PHP Allow URL File Open:  Yes
WP_DEBUG:                 Enabled

Show On Front:            posts
Page On Front:             (#0)
Page For Posts:            (#0)
```
Thank you

**Comment by eri-trabiccolo** [comment] 2017-11-27 07:53
Hi Denzel,
yes I can reproduce this too, under the following conditions:
1) classical style
2) classical grid post list layout
3) infinite scroll enabled in home/blog

same for you?

**Comment by denzelchia** [comment] 2017-11-27 09:19
Hi Rocco,

Yes, under the same conditions as listed by you.

Thank you

**Comment by ghost** [comment] 2017-11-27 20:20
@denzelchia thank you for the detail report and screencast. It helps. @eri-trabiccolo let's schedule a fix for this for the upcoming release. We'll discuss it during the next dev point.
@denzelchia if the user ask for an estimated time of arrival for the fix, you can reply that it should be fixed in the coming days.

**Comment by denzelchia** [comment] 2017-11-28 02:35
@Nikeo 

Ok, will let customer know if he ask for an estimate time of completion. 
Thank you for the update.

**Comment by eri-trabiccolo** [comment] 2017-11-28 08:06
@Nikeo 
actually we did it on purpose because it caused a more important issue as far as I remember. https://github.com/presscustomizr/customizr/blob/v4.0.13/core/init-base.php#L621
So it might take some time.

**Comment by ghost** [comment] 2017-11-28 08:18
@eri-trabiccolo I remember this issue. A first simple fix could simply be to add a notice explaining the problem below the category filter control for Customizr Pro.

**Closed as completed** 2019-11-28 13:51 UTC
Labels: bug, [Priority:urgent], 1-cs, Triage 2019
