### ISSUE TITLE
List Formatting

### ISSUE THREAD

**Issue by ghost** [Nikeo/customizr#1102] opened 2017-07-26 07:44 UTC
> Hi Nicolas,
> 
> Thanks for a great website, which I have been using for some time now. Regarding “modern”, the following questions:
> 
> **– Is it intentional that indents (bullet points and numbering) are no longer indented?**
> 
> Best regards
> Robert

**Comment by eri-trabiccolo** [comment] 2017-07-26 08:00
Cannot reproduce it.
Maybe a plugin resets the indentation?
![list_indentation](https://user-images.githubusercontent.com/7689242/28610583-120fb01c-71e9-11e7-9a9c-39bff4fa0996.png)

Anyway I push a fix to use the same indentation for ul and ol

**Comment by eri-trabiccolo** [comment] 2017-07-26 08:07
Ah I see, we're talking about the right sidebar.
Ok

**Comment by eri-trabiccolo** [comment] 2017-08-02 10:49
fixed in #1105

**Closed as completed by eri-trabiccolo** 2017-08-02 10:49 UTC
Labels: enhancement, fixed, cant-reproduce, 2-ms
